Repository Eika96/strongbox, pull requests merged in 2019-02, with the labels that each got.

#15 Add test documentation to report.md
  doc-resources/Condensation_graph_resolve_argument.svg
  report.md
Labels: documentation

#17 DOC: Remove test requirement for getPathParameter
  report.md
Labels: documentation

#18 Refactor code to use a RepositoryMapping
  strongbox-web-core/src/main/java/org/carlspring/strongbox/config/WebConfig.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/BaseArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/BrowseController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/DefaultExceptionHandler.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/RepositoryMapping.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/RepositoryMappingArgumentResolver.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/TrashController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/ArtifactCoordinateValidatorsManagementController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/HttpConnectionPoolConfigurationManagementController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/configuration/StoragesConfigurationController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/npm/NpmArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/layout/nuget/NugetArtifactController.java
  strongbox-web-core/src/main/java/org/carlspring/strongbox/validation/RepositoryMappingException.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/BrowseControllerTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/configuration/ArtifactCoordinateValidatorsManagementControllerTest.java
Labels: refactoring

#20 Implement tests for RepositoryMappingArgumentResolver.
  strongbox-web-core/src/main/java/org/carlspring/strongbox/controllers/TrashController.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/RepositoryMappingArgumentResolverTest.java
  strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/TrashControllerUndeleteTest.java
Labels: testing

#22 Added UML diagrams
  report.md
Labels: documentation

#24 Added statement of contributions
  report.md
Labels: documentation
